[package]
name = "croncat"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "1.6.1"
color-eyre = "0.6.1"
cosmos-sdk-proto = { version = "0.12.0", features = ["grpc", "cosmwasm"] }
futures-util = "0.3.21"
serde_json = "1.0.81"
tendermint = "0.23.7"
tendermint-rpc = { version = "0.23.7", features = ["websocket-client"] }
tokio = { version = "1.18.0", features = ["macros", "rt-multi-thread", "sync", "signal", "time"] }
tonic = "0.7"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["fmt", "env-filter"] }
url = "2.2.2"
envy = "0.4.2"
serde = { version = "1.0.136", features = ["derive"] } 
dotenv = "0.15.0"
cosmrs = "0.7.0"
cosm-orc = "1.3.4"
cosmwasm-std = { version = "1.0.0" }

cw20-base = "0.13"
cw20 = "0.13"
cw-croncat-core = { version = "0.1.0", git = "https://github.com/CronCats/cw-croncat" }
async-broadcast = "0.4.0"
rand = "0.8.5"
secp256k1 = { version = "0.22.1", features = ["serde", "global-context", "rand-std"] }
anyhow = "1.0"
bip39 = {version = "1.0.1", features = ["rand"] }
[dependencies.prost]
version = "0.10"
[dependencies.prost-types]
version = "0.10"

[dependencies.tendermint-proto]
version = "=0.23.7"


[dev-dependencies]
tracing-test = "0.2.1"
