[package]
name = "croncat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-broadcast = "0.4.0"
async-channel = "1.6.1"
async-trait = "0.1.57"
bip39 = { version = "1.0.1", features = ["rand"] }
chain-registry = "0.1.0"
color-eyre = "0.6.1"
config = { version = "0.13.1", features = ["yaml"] }
cosmos-sdk-proto = { version = "0.12", features = ["grpc", "cosmwasm"] }
cosmrs = { version = "0.7.1", features = ["bip32", "rpc", "cosmwasm"] }
cosmwasm-std = { version = "1.0.0" }
cw-croncat-core = { version = "0.1.0", git = "https://github.com/CronCats/cw-croncat" }
cw-rules-core = { version = "0.1.0", git = "https://github.com/CronCats/cw-croncat" }
cw20 = "0.13"
cw20-base = "0.13"
dotenv = "0.15.0"
envy = "0.4.2"
futures-util = "0.3.21"
indoc = "1.0.7"
prost = "0.10"
prost-types = "0.10"
rand = "0.8.5"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.81"
tendermint = "0.23.7"
tendermint-rpc = { version = "0.23.7", features = ["websocket-client"] }
tokio = { version = "1.18.0", features = ["macros", "rt-multi-thread", "signal", "sync", "time"] }
tokio-retry = "0.3.0"
tonic = "0.7"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["fmt", "env-filter"] }
url = "2.2.2"
whoami = "1.2.3"


[dev-dependencies]
tracing-test = "0.2.1"
